QuestShop/QuestShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

QuestShop/main/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('work', views.work, name='work'),
    path('work/<int:work_id>/', views.detail, name='detail'),
    path('contact', views.contact, name='contact'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestShop/main/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Work(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    main_img = models.ImageField(upload_to="work")
    sub_title = models.CharField(max_length=200)
    content = models.TextField()

class MainImg(models.Model):
    mainImg = models.ImageField(upload_to="main")

class Contact(models.Model):
    company = models.CharField(max_length=20)
    client = models.CharField(max_length=20)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    project = models.CharField(max_length=50)
    detail = models.TextField()



class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['company', 'client', 'phone', 'email', 'project', 'detail']

QuestShop/main/views.py
from django.shortcuts import render, HttpResponseRedirect , get_object_or_404
from .models import MainImg, Work, Contact, ContactForm


# Create your views here.
def index(request):
    mains = MainImg.objects.all()
    return render(request, 'main/index.html', {'mains':mains})

def work(request):
    works = Work.objects.all()
    return render(request, 'main/work.html', {'works' : works})

def detail(request, work_id):
    work = get_object_or_404(Work, pk=work_id)
    return render(request, 'main/detail.html', {'work': work})


def contact(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            form.save()
            return HttpResponseRedirect('/')

            # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()

    return render(request, 'main/contact.html', {'form': form})

QuestShop/main/templates/main/about_us.html
{% extends "main/base.html" %}

{% block content %}

{% load static %}
<img class="d-block w-100" src="{% static 'main/assets/main3.png' %}" alt="About Us">
{% endblock content %}

QuestShop/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QUEST SHOP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% load static %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'main:index' %}"><img src="{% static 'main/assets/logo.png' %}" style="height:100px;"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:work' %}">Works</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
      </li>

    </ul>
  </div>
</nav>

{% block content %}{% endblock content %}
<footer>
    <img class="d-block w-100" src="{% static 'main/assets/footer.png' %}" alt="footer">
</footer>

</body>
</html>

QuestShop/main/templates/main/contact.html
{% extends "main/base.html" %}

{% block content %}
{% load static %}

<form action="{% url 'main:contact' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% endblock content %}

QuestShop/main/templates/main/detail.html
{% extends "main/base.html" %}

{% block content %}
{% load static %}
<img src="{{ work.main_img.url }}" style="width:100%" >
<h1>{{ work.title }}</h1>
<p>{{ work.sub_title }}</p>
<p>{{ work.content }}</p>

<a href="{% url 'main:work' %}"><p>목록으로 돌아가기</p</a>
    
    
    

{% endblock content %}

QuestShop/main/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
{% load static %}


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% if mains %}
      {% for main in mains %}
        {% if forloop.counter0 == 1 %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
        {% else %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"></li>
        {% endif %}
      {% endfor %}
    {% endif %}
  </ol>
  <div class="carousel-inner">

    {% if mains %}
      {% for main in mains %}
        {% if forloop.counter0 == 1 %}
          <div class="carousel-item active">
            <img class="d-block w-100" src="{{ main.mainImg.url }}" alt="slide">
          </div>
        {% else %}
          <div class="carousel-item">
            <img class="d-block w-100" src="{{ main.mainImg.url }}" alt="slide">
          </div>
        {% endif %}

      {% endfor %}
    {% endif %}

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>
{% endblock content %}

QuestShop/main/templates/main/people.html
{% extends "main/base.html" %}

{% block content %}
{% load static %}
{% endblock content %}

QuestShop/main/templates/main/work.html
{% extends "main/base.html" %}

{% block content %}
{% load static %}

<div class="container">
    {% if works %}
        <div class="row">
        {% for work in works %}
            {% if forloop.counter|divisibleby:3 %}
                    <div class="col-md-4">
                      <div class="card mb-4 box-shadow">
                          <a href="{% url 'main:detail' work.id %}">
                              <img class="card-img-top" src="{{ work.main_img.url }}" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22208%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20208%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1645469a878%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A11pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1645469a878%22%3E%3Crect%20width%3D%22208%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2266.9375%22%20y%3D%22117.45%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                          </a>
                        <div class="card-body">
                            <a href="{% url 'main:detail' work.id %}">
                          <p class="card-text">{{ work.content }}</p>
                            </a>
                        </div>
                      </div>
                    </div>
                </div><div class="row">
            {% else %}
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow">
                      <a href="{% url 'main:detail' work.id %}">
                        <img class="card-img-top" src="{{ work.main_img.url }}" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22208%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20208%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1645469a878%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A11pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1645469a878%22%3E%3Crect%20width%3D%22208%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2266.9375%22%20y%3D%22117.45%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                    </a>
                      <div class="card-body">
                          <a href="{% url 'main:detail' work.id %}">
                          <p class="card-text">{{ work.content }}</p>
                          </a>
                        </div>
                </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock content %}